# .github/release.yml

changelog:
  categories:
    - title: New Features
      labels:
        - enhancement
    - title: Fixes
      labels:
        - bug
    - title: Other Changes
      labels:
        - '*'